micronaut:
  application:
    name: scrabble
  router:
    static-resources:
      default:
        enabled: true
        mapping: "/**"
        paths: classpath:public
netty:
  default:
    allocator:
      max-order: 3
