version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk-browsers
    working_directory: ~/repo
    branches:
      only:
        - master
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-gradle-cache-{{ checksum "build.gradle" }}
            - v1-gradle-cache-
      - run: ./gradlew downloadDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-gradle-cache-{{ checksum "build.gradle" }}
      - run: ./gradlew clean build
      - setup_remote_docker
      - run:
          name: Build and push docker image
          command: |
            TAG=1.$CIRCLE_BUILD_NUM
            ./gradlew dockerBuild -PbuildVersion=$TAG
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push jamescookie/scrabble:$TAG
      - add_ssh_keys:
          fingerprints:
            - "6f:e7:84:d4:54:33:07:f8:a1:f7:8a:37:0f:a0:62:a4"
      - run:
          name: Fix host authenticity
          command: touch ~/.ssh/known_hosts; ssh-keyscan $DROPLET_IP >> ~/.ssh/known_hosts
      - run:
          name: Deploy to digital ocean if tests pass and branch is Master
          command: ssh -v $DROPLET_USER@$DROPLET_IP "docker login -u $DOCKER_USER -p $DOCKER_PASS; docker ps -q --filter name='scrabble' | xargs -r docker stop; docker container prune -f; docker run -d -p 8556:8080 --restart=unless-stopped --name scrabble -e VIRTUAL_HOST=scrabble.jamescookie.com,scrabble.jamescookie.co.uk -e LETSENCRYPT_HOST=scrabble.jamescookie.com jamescookie/scrabble:1.$CIRCLE_BUILD_NUM"
