version: 2.1
workflows:
  my-workflow:
    jobs:
      - build:
          context:
            - org-global
          filters:
            branches:
              only: master
jobs:
  build:
    docker:
      - image: cimg/openjdk:21.0.6-browsers
    working_directory: ~/repo
    steps:
      - add_ssh_keys:
          fingerprints:
            - "6f:e7:84:d4:54:33:07:f8:a1:f7:8a:37:0f:a0:62:a4"
      - checkout
      - restore_cache:
          keys:
            - gradle-cache-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
            - gradle-cache-
      - run: ./gradlew --no-daemon --build-cache clean build
      - save_cache:
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper
            - build
          key: gradle-cache-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - setup_remote_docker
      - run:
          name: Build and push docker image
          command: |
            TAG=1.$CIRCLE_BUILD_NUM
            ./gradlew --no-daemon --build-cache dockerBuild -PbuildVersion=$TAG
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push jamescookie/scrabble:$TAG
      - run:
          name: Fix host authenticity
          command: touch ~/.ssh/known_hosts; ssh-keyscan $DROPLET_IP >> ~/.ssh/known_hosts; for f in ~/.ssh/id_rsa_*; do ssh-add $f; done
      - run:
          name: Deploy to digital ocean if tests pass and branch is Master
          command: ssh -o "StrictHostKeyChecking=no" -v $DROPLET_USER@$DROPLET_IP "docker login -u $DOCKER_USER -p $DOCKER_PASS; docker ps -q --filter name='scrabble' | xargs -r docker stop; docker container prune -f; docker run -d -p 8556:8080 --restart=unless-stopped --name scrabble -e VIRTUAL_HOST=scrabble.jamescookie.com,scrabble.jamescookie.co.uk -e LETSENCRYPT_HOST=scrabble.jamescookie.com jamescookie/scrabble:1.$CIRCLE_BUILD_NUM"
